-- Add all new audit action types to the audit_action_type ENUM
-- This migration adds 18 new action types for comprehensive logging

-- Add Tier 1 - Security critical actions
ALTER TYPE audit_action_type ADD VALUE 'LOGIN' AFTER 'OWNER_STATUS_CHANGED';
ALTER TYPE audit_action_type ADD VALUE 'LOGOUT' AFTER 'LOGIN';
ALTER TYPE audit_action_type ADD VALUE 'PASSWORD_CHANGED_OWN' AFTER 'LOGOUT';
ALTER TYPE audit_action_type ADD VALUE 'PASSWORD_RESET_ADMIN' AFTER 'PASSWORD_CHANGED_OWN';

-- Add Tier 2 - Shift operations
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_CREATED' AFTER 'PASSWORD_RESET_ADMIN';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_DELETED' AFTER 'SHIFT_CREATED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_UPDATED' AFTER 'SHIFT_DELETED';

-- Add Tier 2 - Team operations
ALTER TYPE audit_action_type ADD VALUE 'TEAM_CREATED' AFTER 'SHIFT_UPDATED';
ALTER TYPE audit_action_type ADD VALUE 'TEAM_MEMBER_ADDED' AFTER 'TEAM_CREATED';
ALTER TYPE audit_action_type ADD VALUE 'TEAM_MEMBER_REMOVED' AFTER 'TEAM_MEMBER_ADDED';
ALTER TYPE audit_action_type ADD VALUE 'FIREFIGHTER_ROLE_UPDATED' AFTER 'TEAM_MEMBER_REMOVED';
ALTER TYPE audit_action_type ADD VALUE 'FIREFIGHTER_DELETED' AFTER 'FIREFIGHTER_ROLE_UPDATED';
ALTER TYPE audit_action_type ADD VALUE 'TEAM_MEMBERS_REORDERED' AFTER 'FIREFIGHTER_DELETED';

-- Add Tier 2 - Shift assignments
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_ASSIGNMENT_CREATED' AFTER 'TEAM_MEMBERS_REORDERED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_ASSIGNMENT_DELETED' AFTER 'SHIFT_ASSIGNMENT_CREATED';

-- Add Tier 3 - Shift notes
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_NOTE_CREATED' AFTER 'SHIFT_ASSIGNMENT_DELETED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_NOTE_UPDATED' AFTER 'SHIFT_NOTE_CREATED';

-- Add Tier 3 - Notifications
ALTER TYPE audit_action_type ADD VALUE 'NOTIFICATION_SENT_MANUAL' AFTER 'SHIFT_NOTE_UPDATED';
