-- Add SHIFT_ASSIGNMENT_CREATED and SHIFT_ASSIGNMENT_DELETED to audit_action_type enum
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_ASSIGNMENT_CREATED' BEFORE 'SHIFT_NOTE_CREATED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_ASSIGNMENT_DELETED' BEFORE 'SHIFT_NOTE_CREATED';
