-- Add SHIFT_NOTE_CREATED, SHIFT_NOTE_UPDATED, SHIFT_NOTE_DELETED to audit_action_type enum
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_NOTE_CREATED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_NOTE_UPDATED';
ALTER TYPE audit_action_type ADD VALUE 'SHIFT_NOTE_DELETED';
